create table if not exists public.landing_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  page text not null default 'landing',
  user_id uuid null references auth.users (id) on delete set null,
  user_email text null,
  selected_features text[] not null default '{}',
  comments text null check (comments is null or char_length(comments) <= 2000),
  preview_snapshot jsonb not null default '{}'::jsonb
);

alter table public.landing_feedback enable row level security;

create policy "Anyone can submit landing feedback"
on public.landing_feedback
for insert
to anon, authenticated
with check (true);
